
name: Deploy to production

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  install_deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Install Node.js v12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vendor
          path: node_modules
  build:
    name: Build for production
    needs: install_deps
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Generate static files
        run: yarn generate
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build_files
          path: dist
  deploy:
    name: Deploy to production
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.4
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: sulfuron-guilds
          TARGET_BRANCH: master