name: Deploy to staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://sulfuron-guilds-staging.web.app/
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Install Node.js v12
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate static files
        run: yarn generate:staging
      - name: Deploy front-end to Firebase
        uses: lowply/deploy-firebase@v0.0.4
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: sulfuron-guilds-staging
          TARGET_BRANCH: develop
