name: Test on Pull Requests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop 

jobs:
  jest:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Install Node.js v12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}s
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test