name: Test on Pull Requests

on:
  push:
    branches:
      - actions
  pull_request:
    branches:
      - master
      - develop 

jobs:
  jest:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Install Node.js v12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test